### ISSUE TITLE
Print slides/export as PDF

### ISSUE THREAD

**Issue by nathangibson** [jirelations/Millennial#46]
See https://revealjs.com/pdf-export/ 
Slides can be print-formatted by adding /?print-pdf to the end of the URL. Maybe we put this in sidebar menu? 
An actual "print" button (if needed) can use the following code 
```
<button onclick="window.print();return false;" value="print">Print</button>
```
For PDFs users would then need to select "Save as PDF"

Alternatively we just add an alternate "view" for the content that doesn't use the `reveal` layout.

**Comment by YSL4L** [comment]
During testing, I encountered a bug linked to the Prettier Code Formatting plugin in Visual Studio. Normally, this plugin auto-formats the code when I save a file, which helps maintain clean code. However, when I edit and save the reveal.html file, it seems that the plugin corrupts the code, causing the slides to stop loading. I'll make sure to include this in the documentation.

**Comment by nathangibson** [comment]
@YSL4L We'll try to finish this up for the WiSe version
